use_frameworks!

target 'ZYMyTestLibrary_Example' do
  pod 'ZYMyTestLibrary', :path => '../'

  target 'ZYMyTestLibrary_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
